export type Dish = {
  name: string;
  description: string;
  price: string;
  image: string;
  tags?: string[];
  ingredients: string;
  allergens: string;
  portion: string;
  category?: string;
};

export type MenuItem = Omit<Dish, 'category'> & { category: string };

export type Restaurant = {
  id: string;
  name: string;
  welcome_message: string;
  image: string;
  menu_categories: string[];
  featured_dishes: Dish[];
  menu_items: MenuItem[];
};

export const restaurants: Restaurant[] = [
  {
    id: "korean",
    name: "Estilo Coreano",
    welcome_message: "Bem-vindo ao Estilo Coreano - Nossos Pratos de Assinatura",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    menu_categories: [ "Entradas", "Pratos Principais", "Sobremesas", "Bebidas" ],
    featured_dishes: [
      {
        name: "Bibimbap",
        description: "Arroz misturado com vegetais, carne e ovo.",
        price: "R$ 79,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Assinatura" ],
        ingredients: "Arroz, carne, vegetais, ovo, molho gochujang",
        allergens: "Ovos, Soja",
        portion: "Serve 1 pessoa",
        category: "Pratos Principais",
      },
      {
        name: "Kimchi",
        description: "Repolho fermentado apimentado, tradicional coreano.",
        price: "R$ 19,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Vegano" ],
        ingredients: "Repolho, pimenta, alho, gengibre",
        allergens: "Nenhum",
        portion: "Tigela pequena",
        category: "Entradas",
      },
      {
        name: "Bulgogi",
        description: "Carne marinada grelhada ao estilo coreano.",
        price: "R$ 89,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Clássico" ],
        ingredients: "Carne bovina, molho de soja, alho, açúcar, gergelim",
        allergens: "Soja, Gergelim",
        portion: "Serve 1 pessoa",
        category: "Pratos Principais",
      },
      {
        name: "Tteokbokki",
        description: "Bolinhos de arroz apimentados em molho gochujang.",
        price: "R$ 39,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Picante" ],
        ingredients: "Bolo de arroz, molho gochujang, cebolinha",
        allergens: "Soja",
        portion: "Prato pequeno",
        category: "Entradas",
      },
      {
        name: "Sundubu Jjigae",
        description: "Ensopado de tofu macio apimentado.",
        price: "R$ 49,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Apimentado" ],
        ingredients: "Tofu, vegetais, ovo, pimenta",
        allergens: "Ovos, Soja",
        portion: "Serve 1 pessoa",
        category: "Pratos Principais",
      },
    ],
    menu_items: [
      // Entradas
      {
        category: "Entradas",
        name: "Kimchi",
        description: "Repolho fermentado apimentado, tradicional coreano.",
        price: "R$ 19,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Vegano" ],
        ingredients: "Repolho, pimenta, alho, gengibre",
        allergens: "Nenhum",
        portion: "Tigela pequena",
      },
      {
        category: "Entradas",
        name: "Tteokbokki",
        description: "Bolinhos de arroz apimentados em molho gochujang.",
        price: "R$ 39,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Picante" ],
        ingredients: "Bolo de arroz, molho gochujang, cebolinha",
        allergens: "Soja",
        portion: "Prato pequeno",
      },
      {
        category: "Entradas",
        name: "Pajeon",
        description: "Panqueca coreana de cebolinha.",
        price: "R$ 29,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Vegetariano" ],
        ingredients: "Farinha, cebolinha, ovo, molho de soja",
        allergens: "Ovos, Soja, Glúten",
        portion: "1 unidade",
      },
      {
        category: "Entradas",
        name: "Mandu",
        description: "Guioza coreano recheado com carne e vegetais.",
        price: "R$ 34,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Frito" ],
        ingredients: "Carne, vegetais, farinha, alho",
        allergens: "Glúten",
        portion: "6 unidades",
      },
      {
        category: "Entradas",
        name: "Japchae",
        description: "Macarrão de batata-doce salteado com vegetais e carne.",
        price: "R$ 44,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Clássico" ],
        ingredients: "Macarrão de batata-doce, carne, vegetais, molho de soja",
        allergens: "Soja",
        portion: "Prato pequeno",
      },
      {
        category: "Entradas",
        name: "Haemul Pajeon",
        description: "Panqueca de frutos do mar e cebolinha.",
        price: "R$ 39,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Frutos do Mar" ],
        ingredients: "Farinha, frutos do mar, cebolinha, ovo",
        allergens: "Ovos, Glúten, Frutos do Mar",
        portion: "1 unidade",
      },
      {
        category: "Entradas",
        name: "Gyeran Mari",
        description: "Omelete enrolado coreano com vegetais.",
        price: "R$ 24,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Ovo" ],
        ingredients: "Ovo, cenoura, cebolinha, pimentão",
        allergens: "Ovos",
        portion: "4 fatias",
      },
      {
        category: "Entradas",
        name: "Oi Muchim",
        description: "Salada de pepino apimentada.",
        price: "R$ 22,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Refrescante" ],
        ingredients: "Pepino, pimenta, alho, vinagre",
        allergens: "Nenhum",
        portion: "Tigela pequena",
      },
      {
        category: "Entradas",
        name: "Kimbap",
        description: "Rolinhos de arroz e vegetais enrolados em alga.",
        price: "R$ 34,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Vegetariano" ],
        ingredients: "Arroz, vegetais, alga, ovo",
        allergens: "Ovos",
        portion: "8 fatias",
      },
      {
        category: "Entradas",
        name: "Sujeonggwa (Sobremesa)",
        description: "Bebida doce de canela e gengibre, servida gelada.",
        price: "R$ 14,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Doce" ],
        ingredients: "Canela, gengibre, açúcar, caqui seco",
        allergens: "Nenhum",
        portion: "Copo pequeno",
      },
      // Pratos Principais
      {
        category: "Pratos Principais",
        name: "Bibimbap",
        description: "Arroz misturado com vegetais, carne e ovo.",
        price: "R$ 79,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Assinatura" ],
        ingredients: "Arroz, carne, vegetais, ovo, molho gochujang",
        allergens: "Ovos, Soja",
        portion: "Serve 1 pessoa",
      },
      {
        category: "Pratos Principais",
        name: "Bulgogi",
        description: "Carne marinada grelhada ao estilo coreano.",
        price: "R$ 89,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Clássico" ],
        ingredients: "Carne bovina, molho de soja, alho, açúcar, gergelim",
        allergens: "Soja, Gergelim",
        portion: "Serve 1 pessoa",
      },
      {
        category: "Pratos Principais",
        name: "Sundubu Jjigae",
        description: "Ensopado de tofu macio apimentado.",
        price: "R$ 49,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Apimentado" ],
        ingredients: "Tofu, vegetais, ovo, pimenta",
        allergens: "Ovos, Soja",
        portion: "Serve 1 pessoa",
      },
      {
        category: "Pratos Principais",
        name: "Samgyeopsal",
        description: "Barriga de porco grelhada, servida com acompanhamentos.",
        price: "R$ 99,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Churrasco" ],
        ingredients: "Barriga de porco, alho, cebolinha, gergelim",
        allergens: "Gergelim",
        portion: "Serve 2 pessoas",
      },
      {
        category: "Pratos Principais",
        name: "Galbi",
        description: "Costela bovina marinada e grelhada.",
        price: "R$ 109,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Churrasco" ],
        ingredients: "Costela bovina, molho de soja, alho, açúcar, gergelim",
        allergens: "Soja, Gergelim",
        portion: "Serve 1 pessoa",
      },
      {
        category: "Pratos Principais",
        name: "Jjajangmyeon",
        description: "Macarrão com molho de feijão preto.",
        price: "R$ 59,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Clássico" ],
        ingredients: "Macarrão, molho de feijão preto, carne suína, cebola",
        allergens: "Glúten, Soja",
        portion: "Serve 1 pessoa",
      },
      {
        category: "Pratos Principais",
        name: "Dakgangjeong",
        description: "Frango crocante agridoce.",
        price: "R$ 69,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Frito" ],
        ingredients: "Frango, farinha, molho agridoce, gergelim",
        allergens: "Glúten, Gergelim",
        portion: "Serve 1 pessoa",
      },
      {
        category: "Pratos Principais",
        name: "Kimchi Jjigae",
        description: "Ensopado apimentado de kimchi com carne de porco.",
        price: "R$ 54,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Apimentado" ],
        ingredients: "Kimchi, carne de porco, tofu, vegetais",
        allergens: "Soja",
        portion: "Serve 1 pessoa",
      },
      {
        category: "Pratos Principais",
        name: "Naengmyeon",
        description: "Macarrão gelado em caldo refrescante.",
        price: "R$ 49,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Refrescante" ],
        ingredients: "Macarrão de trigo sarraceno, ovo, pepino, caldo",
        allergens: "Ovos, Glúten",
        portion: "Serve 1 pessoa",
      },
      {
        category: "Pratos Principais",
        name: "Jjamppong",
        description: "Macarrão apimentado com frutos do mar.",
        price: "R$ 69,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Picante", "Frutos do Mar" ],
        ingredients: "Macarrão, frutos do mar, vegetais, pimenta",
        allergens: "Glúten, Frutos do Mar",
        portion: "Serve 1 pessoa",
      },
      // Sobremesas
      {
        category: "Sobremesas",
        name: "Hotteok",
        description: "Panqueca doce recheada com açúcar e nozes.",
        price: "R$ 19,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Doce" ],
        ingredients: "Farinha, açúcar, nozes, canela",
        allergens: "Glúten, Nozes",
        portion: "2 unidades",
      },
      {
        category: "Sobremesas",
        name: "Bingsu",
        description: "Raspadinha de gelo com leite condensado e frutas.",
        price: "R$ 29,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Refrescante" ],
        ingredients: "Gelo, leite condensado, frutas",
        allergens: "Leite",
        portion: "Tigela média",
      },
      {
        category: "Sobremesas",
        name: "Yakgwa",
        description: "Biscoito tradicional de mel.",
        price: "R$ 14,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Doce" ],
        ingredients: "Farinha, mel, óleo de gergelim",
        allergens: "Glúten, Gergelim",
        portion: "4 unidades",
      },
      {
        category: "Sobremesas",
        name: "Tteok",
        description: "Bolo de arroz doce coreano.",
        price: "R$ 17,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Tradicional" ],
        ingredients: "Arroz, feijão doce",
        allergens: "Nenhum",
        portion: "6 fatias",
      },
      {
        category: "Sobremesas",
        name: "Patbingsu",
        description: "Raspadinha de gelo com feijão doce e frutas.",
        price: "R$ 29,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Refrescante" ],
        ingredients: "Gelo, feijão doce, frutas",
        allergens: "Nenhum",
        portion: "Tigela média",
      },
      {
        category: "Sobremesas",
        name: "Dasik",
        description: "Biscoito de chá coreano.",
        price: "R$ 12,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Chá" ],
        ingredients: "Farinha de arroz, mel, chá verde",
        allergens: "Glúten",
        portion: "6 unidades",
      },
      {
        category: "Sobremesas",
        name: "Hwajeon",
        description: "Panqueca de flores com mel.",
        price: "R$ 15,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Floral" ],
        ingredients: "Farinha de arroz, flores comestíveis, mel",
        allergens: "Glúten",
        portion: "4 unidades",
      },
      {
        category: "Sobremesas",
        name: "Injeolmi",
        description: "Bolo de arroz polvilhado com farinha de soja.",
        price: "R$ 16,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Tradicional" ],
        ingredients: "Arroz, farinha de soja, açúcar",
        allergens: "Soja",
        portion: "6 fatias",
      },
      {
        category: "Sobremesas",
        name: "Sikhye (Sobremesa)",
        description: "Bebida doce de arroz fermentado.",
        price: "R$ 13,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Bebida", "Doce" ],
        ingredients: "Arroz, açúcar, cevada",
        allergens: "Glúten",
        portion: "Copo pequeno",
      },
      {
        category: "Sobremesas",
        name: "Yaksik",
        description: "Arroz doce com castanhas e frutas secas.",
        price: "R$ 18,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Doce" ],
        ingredients: "Arroz, castanha, frutas secas, mel",
        allergens: "Castanhas",
        portion: "Tigela pequena",
      },
      // Bebidas
      {
        category: "Bebidas",
        name: "Sujeonggwa (Bebida)",
        description: "Bebida doce de canela e gengibre, servida gelada.",
        price: "R$ 14,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Doce" ],
        ingredients: "Canela, gengibre, açúcar, caqui seco",
        allergens: "Nenhum",
        portion: "Copo pequeno",
      },
      {
        category: "Bebidas",
        name: "Sikhye (Bebida)",
        description: "Bebida doce de arroz fermentado.",
        price: "R$ 13,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Doce" ],
        ingredients: "Arroz, açúcar, cevada",
        allergens: "Glúten",
        portion: "Copo pequeno",
      },
      {
        category: "Bebidas",
        name: "Soju",
        description: "Destilado coreano tradicional.",
        price: "R$ 24,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Alcoólico" ],
        ingredients: "Arroz, cevada, batata-doce",
        allergens: "Nenhum",
        portion: "Garrafa 360ml",
      },
      {
        category: "Bebidas",
        name: "Makgeolli",
        description: "Vinho de arroz levemente gaseificado.",
        price: "R$ 19,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Alcoólico" ],
        ingredients: "Arroz, água, fermento",
        allergens: "Nenhum",
        portion: "Copo 200ml",
      },
      {
        category: "Bebidas",
        name: "Chá de Ginseng",
        description: "Chá tradicional coreano de ginseng.",
        price: "R$ 12,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Chá" ],
        ingredients: "Ginseng, água, mel",
        allergens: "Nenhum",
        portion: "Xícara",
      },
      {
        category: "Bebidas",
        name: "Chá de Yujacha",
        description: "Chá doce de yuzu coreano.",
        price: "R$ 12,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Chá", "Cítrico" ],
        ingredients: "Yuzu, mel, água",
        allergens: "Nenhum",
        portion: "Xícara",
      },
      {
        category: "Bebidas",
        name: "Chá de Barley (Bori-cha)",
        description: "Chá de cevada torrada, servido quente ou frio.",
        price: "R$ 10,90",
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80",
        tags: [ "Chá" ],
        ingredients: "Cevada, água",
        allergens: "Glúten",
        portion: "Xícara",
      },
      {
        category: "Bebidas",
        name: "Milkis",
        description: "Refrigerante coreano de leite.",
        price: "R$ 9,90",
        image: "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80",
        tags: [ "Refrigerante" ],
        ingredients: "Leite, água gaseificada, açúcar",
        allergens: "Leite",
        portion: "Lata 250ml",
      },
      {
        category: "Bebidas",
        name: "Chá de Jujuba",
        description: "Chá doce feito de jujuba coreana.",
        price: "R$ 11,90",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
        tags: [ "Chá" ],
        ingredients: "Jujuba, água, mel",
        allergens: "Nenhum",
        portion: "Xícara",
      },
      {
        category: "Bebidas",
        name: "Chá de Gengibre",
        description: "Chá quente de gengibre e mel.",
        price: "R$ 11,90",
        image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80",
        tags: [ "Chá" ],
        ingredients: "Gengibre, mel, água",
        allergens: "Nenhum",
        portion: "Xícara",
      }
    ],
  },
  {
    id: "japanese",
    name: "Japanese Style",
    welcome_message: "Welcome to Japanese Style - Our Signature Dishes",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    menu_categories: [ "Starters", "Main Dishes", "Desserts", "Drinks" ],
    featured_dishes: [
      {
        name: "Sushi Platter",
        description: "Assorted fresh sushi and sashimi.",
        price: "22.99",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80",
        tags: [ "Chef's Choice" ],
        ingredients: "Rice, fish, seaweed, vegetables",
        allergens: "Fish, Soy",
        portion: "Serves 1",
        category: "Main Dishes",
      },
    ],
    menu_items: [
      {
        category: "Starters",
        name: "Edamame",
        description: "Steamed soybeans with sea salt.",
        price: "4.99",
        image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80",
        tags: [ "Vegan" ],
        ingredients: "Soybeans, salt",
        allergens: "Soy",
        portion: "Small bowl",
      },
      {
        category: "Main Dishes",
        name: "Sushi Platter",
        description: "Assorted fresh sushi and sashimi.",
        price: "22.99",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80",
        tags: [ "Chef's Choice" ],
        ingredients: "Rice, fish, seaweed, vegetables",
        allergens: "Fish, Soy",
        portion: "Serves 1",
      },
    ],
  },
  {
    id: "chinese",
    name: "Chinese Style",
    welcome_message: "Welcome to Chinese Style - Our Signature Dishes",
    image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=800&q=80",
    menu_categories: [ "Starters", "Main Dishes", "Desserts", "Drinks" ],
    featured_dishes: [
      {
        name: "Peking Duck",
        description: "Crispy duck served with pancakes and hoisin sauce.",
        price: "29.99",
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        tags: [ "Classic" ],
        ingredients: "Duck, pancakes, hoisin sauce, cucumber, scallion",
        allergens: "Gluten, Soy",
        portion: "Serves 2",
        category: "Main Dishes",
      },
    ],
    menu_items: [
      {
        category: "Starters",
        name: "Spring Rolls",
        description: "Crispy rolls with vegetables and pork.",
        price: "6.99",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=400&q=80",
        tags: [ "Popular" ],
        ingredients: "Vegetables, pork, flour, oil",
        allergens: "Gluten",
        portion: "2 pieces",
      },
      {
        category: "Main Dishes",
        name: "Peking Duck",
        description: "Crispy duck served with pancakes and hoisin sauce.",
        price: "29.99",
        image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80",
        tags: [ "Classic" ],
        ingredients: "Duck, pancakes, hoisin sauce, cucumber, scallion",
        allergens: "Gluten, Soy",
        portion: "Serves 2",
      },
    ],
  },
];

export const restaurantMap = Object.fromEntries(restaurants.map(r => [ r.id, r ])); 