export type Dish = {
  name: string;
  description: string;
  price: string;
  image: string;
  tags?: string[];
  ingredients: string;
  allergens: string;
  portion: string;
  category?: string;
};

export type MenuItem = Omit<Dish, 'category'> & { category: string };

export const appData = {
  restaurant: {
    name: "A Colher de Ouro",
    welcome_message: "Bem-vindo à Colher de Ouro - Nossos Pratos Assinatura",
  },
  featured_dishes: [
    {
      name: "Salmão Grelhado",
      description: "Salmão do Atlântico fresco grelhado à perfeição com ervas e limão",
      price: "28.99",
      image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
      tags: ["Especial do Chef"],
      ingredients: "Salmão do Atlântico, ervas, limão, azeite de oliva",
      allergens: "Contém: Peixe",
      portion: "Serve 1",
      category: "Pratos Principais",
    },
    {
      name: "Beef Wellington",
      description: "Filé de carne envolto em massa folhada com duxelles de cogumelos",
      price: "45.99",
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80",
      tags: ["Premium"],
      ingredients: "Filé mignon, massa folhada, cogumelos, ervas",
      allergens: "Contém: Glúten, Ovos",
      portion: "Serve 1",
      category: "Pratos Principais",
    },
    {
      name: "Lagosta Thermidor",
      description: "Clássico francês de lagosta com molho cremoso e queijo",
      price: "52.99",
      image: "https://images.unsplash.com/photo-1559737558-2cc3739e4093?auto=format&fit=crop&w=400&q=80",
      tags: ["Premium"],
      ingredients: "Lagosta, creme de leite, queijo, ervas, conhaque",
      allergens: "Contém: Crustáceos, Laticínios",
      portion: "Serve 1",
      category: "Pratos Principais",
    },
    {
      name: "Risoto de Trufas",
      description: "Arroz arbório cremoso com trufa negra e parmesão",
      price: "38.99",
      image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
      tags: ["Vegetariano"],
      ingredients: "Arroz arbório, trufa negra, parmesão, vinho branco",
      allergens: "Contém: Laticínios",
      portion: "Serve 1",
      category: "Pratos Principais",
    },
    {
      name: "Bolo de Chocolate com Recheio Cremoso",
      description: "Bolo de chocolate quente com centro derretido",
      price: "12.99",
      image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=400&q=80",
      tags: ["Sobremesa"],
      ingredients: "Chocolate amargo, ovos, manteiga, farinha, açúcar",
      allergens: "Contém: Glúten, Ovos, Laticínios",
      portion: "Serve 1",
      category: "Sobremesas",
    },
  ],
  menu_categories: ["Entradas", "Pratos Principais", "Sobremesas", "Bebidas"],
  menu_items: [
    {
      category: "Entradas",
      name: "Lula Crocante",
      description: "Anéis de lula macios empanados e fritos, servidos com molho marinara",
      price: "14.99",
      image: "https://images.unsplash.com/photo-1559737558-2cc3739e4093?auto=format&fit=crop&w=400&q=80",
      tags: ["Frutos do Mar"],
      ingredients: "Lula, farinha, ovos, molho marinara, ervas",
      allergens: "Contém: Frutos do Mar, Glúten, Ovos",
      portion: "Serve 1-2",
    },
    {
      category: "Entradas",
      name: "Salada de Burrata",
      description: "Queijo burrata fresco com tomates heirloom e manjericão",
      price: "16.99",
      image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80",
      tags: ["Vegetariano"],
      ingredients: "Burrata, tomates, manjericão, azeite de oliva, balsâmico",
      allergens: "Contém: Laticínios",
      portion: "Serve 1",
    },
    {
      category: "Pratos Principais",
      name: "Salmão Grelhado",
      description: "Salmão do Atlântico fresco grelhado à perfeição com ervas e limão",
      price: "28.99",
      image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=400&q=80",
      tags: ["Especial do Chef"],
      ingredients: "Salmão do Atlântico, ervas, limão, azeite de oliva",
      allergens: "Contém: Peixe",
      portion: "Serve 1",
    },
    {
      category: "Pratos Principais",
      name: "Bife de Ancho",
      description: "Bife de ancho premium preparado ao seu gosto",
      price: "42.99",
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80",
      tags: ["Premium"],
      ingredients: "Bife de ancho, ervas, alho, manteiga",
      allergens: "Contém: Laticínios",
      portion: "Serve 1",
    },
    {
      category: "Sobremesas",
      name: "Bolo de Chocolate com Recheio Cremoso",
      description: "Bolo de chocolate quente com centro derretido",
      price: "12.99",
      image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=400&q=80",
      tags: ["Sobremesa"],
      ingredients: "Chocolate amargo, ovos, manteiga, farinha, açúcar",
      allergens: "Contém: Glúten, Ovos, Laticínios",
      portion: "Serve 1",
    },
    {
      category: "Sobremesas",
      name: "Tiramisù",
      description: "Clássica sobremesa italiana com café e mascarpone",
      price: "11.99",
      image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=400&q=80",
      tags: ["Clássico"],
      ingredients: "Mascarpone, café, biscoito champagne, cacau",
      allergens: "Contém: Laticínios, Ovos, Glúten",
      portion: "Serve 1",
    },
    {
      category: "Bebidas",
      name: "Vinho da Casa",
      description: "Seleção de vinhos tintos e brancos",
      price: "8.99",
      image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=400&q=80",
      tags: ["Alcoólico"],
      ingredients: "Uvas, sulfitos",
      allergens: "Contém: Sulfitos",
      portion: "Taça de 150ml",
    },
    {
      category: "Bebidas",
      name: "Cerveja Artesanal",
      description: "Seleção de cervejas artesanais locais",
      price: "6.99",
      image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=400&q=80",
      tags: ["Alcoólico"],
      ingredients: "Lúpulo, cevada, levedura",
      allergens: "Contém: Glúten",
      portion: "Garrafa de 355ml",
    },
  ],
}; 