name: Check Secrets Configuration

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        run: |
          echo "🔍 Verificando configuração dos secrets..."
          echo ""
          
          # Verificar TELEGRAM_BOT_TOKEN
          if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
            echo "✅ TELEGRAM_BOT_TOKEN: CONFIGURADO"
            echo "   Comprimento: ${#TELEGRAM_BOT_TOKEN} caracteres"
            echo "   Primeiros 20 chars: ${TELEGRAM_BOT_TOKEN:0:20}..."
          else
            echo "❌ TELEGRAM_BOT_TOKEN: NÃO CONFIGURADO"
          fi
          
          echo ""
          
          # Verificar TELEGRAM_CHAT_ID
          if [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            echo "✅ TELEGRAM_CHAT_ID: CONFIGURADO"
            echo "   Valor: $TELEGRAM_CHAT_ID"
            echo "   Comprimento: ${#TELEGRAM_CHAT_ID} caracteres"
          else
            echo "❌ TELEGRAM_CHAT_ID: NÃO CONFIGURADO"
          fi
          
          echo ""
          echo "📋 Resumo:"
          echo "   - Token configurado: ${{ secrets.TELEGRAM_BOT_TOKEN != '' && '✅ Sim' || '❌ Não' }}"
          echo "   - Chat ID configurado: ${{ secrets.TELEGRAM_CHAT_ID != '' && '✅ Sim' || '❌ Não' }}"
          
          # Verificar se ambos estão configurados
          if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            echo "🎯 Status: AMBOS CONFIGURADOS - Pode testar as notificações!"
          else
            echo "🚨 Status: SECRETS INCOMPLETOS - Configure os secrets primeiro!"
            exit 1
          fi
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Test API connection
        run: |
          echo "🔗 Testando conexão com a API do Telegram..."
          
          # Testar se o bot existe
          BOT_INFO=$(curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe")
          echo "📱 Informações do bot:"
          echo "$BOT_INFO"
          
          if echo "$BOT_INFO" | grep -q '"ok":true'; then
            echo "✅ Bot encontrado e válido!"
            
            # Testar se pode enviar mensagem (sem enviar de fato)
            CHAT_INFO=$(curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getChat?chat_id=${TELEGRAM_CHAT_ID}")
            echo "👥 Informações do chat:"
            echo "$CHAT_INFO"
            
            if echo "$CHAT_INFO" | grep -q '"ok":true'; then
              echo "✅ Chat encontrado e acessível!"
            else
              echo "❌ Chat não encontrado ou inacessível"
              echo "   Verifique se o bot foi adicionado ao grupo/canal"
            fi
          else
            echo "❌ Bot não encontrado ou token inválido"
            echo "   Verifique o token do bot"
          fi
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
