name: Notify Telegram - Playwright (workflow_run)

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types: [completed]

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        id: msg
        run: |
          STATUS="${{ github.event.workflow_run.conclusion }}"
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          ACTOR="${{ github.event.workflow_run.actor.login }}"
          URL="${{ github.event.workflow_run.html_url }}"
          UPDATED_AT="${{ github.event.workflow_run.updated_at }}"

          if [ "$STATUS" = "success" ]; then
            STATUS_EMOJI="✅ Sucesso"
          elif [ "$STATUS" = "failure" ]; then
            STATUS_EMOJI="❌ Falha"
          elif [ "$STATUS" = "cancelled" ]; then
            STATUS_EMOJI="⚠️ Cancelado"
          else
            STATUS_EMOJI="$STATUS"
          fi

          echo "status_emoji=$STATUS_EMOJI" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "actor=$ACTOR" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "updated_at=$UPDATED_AT" >> $GITHUB_OUTPUT

      - name: Send Telegram notification
        uses: appleboy/telegram-action@v0.0.9
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🤖 **GitHub Actions - Playwright Tests**

            📋 **Status:** ${{ steps.msg.outputs.status_emoji }}

            🌿 **Branch:** ${{ steps.msg.outputs.branch }}

            👤 **Autor:** ${{ steps.msg.outputs.actor }}

            🔗 **Ver execução:** [Abrir execução](${{ steps.msg.outputs.url }})

            ⏰ **Executado em:** ${{ steps.msg.outputs.updated_at }}
