name: Playwright Tests - Development Server

on:
  push:
    branches: [ main, develop, feature/*, bugfix/* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Start development server
      run: |
        npm run dev &
        echo "Waiting for dev server to start..."
        sleep 30
        echo "Dev server should be ready now"
        curl -f http://localhost:3000 || exit 1
      env:
        CI: true
    
    - name: Run Playwright tests
      run: npx playwright test --project=chromium --reporter=line
      env:
        CI: true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-dev-results
        path: |
          playwright-report/
          test-results/
        retention-days: 7
